# -*- coding: utf-8 -*-
"""Fresh_Scrotch_Using_SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z2NKX9GD1s5yZ2cTxZ3MQ625x0BQYolO
"""

import os
import numpy as np
import cv2
import matplotlib.pyplot as plt
import random
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

DIRECTORY = r"/content/drive/MyDrive/leaf/Leaf_2"
##CATAGORIES = ['Strawberry_fresh','Strawberry_scrotch','Apple___Apple_scab','Apple___Black_rot','Apple___Cedar_apple_rust','Apple___healthy']
CATAGORIES = ['Healthy_Leaf','Unhealthy_Leaf']

data = []

for categories in CATAGORIES:
    folder=os.path.join(DIRECTORY,categories)
    print(folder)
    label=CATAGORIES.index(categories)


    for img in os.listdir(folder):
        img=os.path.join(folder,img)
        img_arr=cv2.imread(img)
        img_arr=cv2.resize(img_arr,(100,100))
        img_arr=np.array(img_arr).flatten()
        data.append([img_arr,label])

random.shuffle(data)

x=[]
y=[]


for features,label in data:
    x.append(features)
    y.append(label)

#X= np.array(x)
#Y=np.array(y)

#X

#X = X/255

#X.shape

xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size=0.25)

model = SVC(C=1,kernel='poly',gamma= 'auto')

history = model.fit(xtrain, ytrain)

prediction = model.predict(xtest)

accuracy = model.score(xtest,ytest)

CATAGORIES = ['Healthy_Leaf','Unhealthy_Leaf']

print('Accuracy: ', accuracy)

print('Prediction is: ', CATAGORIES[prediction[0]])